services:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      GATEWAY_PORT: "3000"
      REPLICA_MAP: "replica1=http://replica1:4001,replica2=http://replica2:4002,replica3=http://replica3:4003"
    depends_on:
      - replica1
      - replica2
      - replica3
    networks:
      - raft-net
    volumes:
      - ./:/app
      - /app/node_modules

  replica1:
    build:
      context: .
      dockerfile: services/replica1/Dockerfile
    environment:
      REPLICA_ID: "replica1"
      PORT: "4001"
      PEERS: "replica2=http://replica2:4002,replica3=http://replica3:4003"
      GATEWAY_URL: "http://gateway:3000"
      HEARTBEAT_INTERVAL_MS: "150"
      ELECTION_TIMEOUT_MIN_MS: "500"
      ELECTION_TIMEOUT_MAX_MS: "800"
      HEARTBEAT_LOG_INTERVAL_MS: "4000"
    ports:
      - "4001:4001"
    networks:
      - raft-net
    volumes:
      - ./:/app
      - /app/node_modules

  replica2:
    build:
      context: .
      dockerfile: services/replica2/Dockerfile
    environment:
      REPLICA_ID: "replica2"
      PORT: "4002"
      PEERS: "replica1=http://replica1:4001,replica3=http://replica3:4003"
      GATEWAY_URL: "http://gateway:3000"
      HEARTBEAT_INTERVAL_MS: "150"
      ELECTION_TIMEOUT_MIN_MS: "500"
      ELECTION_TIMEOUT_MAX_MS: "800"
      HEARTBEAT_LOG_INTERVAL_MS: "4000"
    ports:
      - "4002:4002"
    networks:
      - raft-net
    volumes:
      - ./:/app
      - /app/node_modules

  replica3:
    build:
      context: .
      dockerfile: services/replica3/Dockerfile
    environment:
      REPLICA_ID: "replica3"
      PORT: "4003"
      PEERS: "replica1=http://replica1:4001,replica2=http://replica2:4002"
      GATEWAY_URL: "http://gateway:3000"
      HEARTBEAT_INTERVAL_MS: "150"
      ELECTION_TIMEOUT_MIN_MS: "500"
      ELECTION_TIMEOUT_MAX_MS: "800"
      HEARTBEAT_LOG_INTERVAL_MS: "4000"
    ports:
      - "4003:4003"
    networks:
      - raft-net
    volumes:
      - ./:/app
      - /app/node_modules

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DASHBOARD_PORT: "3001"
      REPLICA_URLS: "http://gateway:3000,http://replica1:4001,http://replica2:4002,http://replica3:4003"
    depends_on:
      - replica1
      - replica2
      - replica3
    networks:
      - raft-net
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  raft-net:
    driver: bridge
